# LangChain Messages:
# 1. Messages are the basic units of communication between users, AI models, and tools.
# 2. HumanMessage represents a message sent by the user.
# 3. AIMessage represents a response generated by the AI model.
# 4. SystemMessage provides instructions and behavior guidelines to the AI model.
# 5. ToolMessage contains the result returned by a tool called by the AI.
# 6. Messages generally contain content, which holds the actual text or data.
# 7. Messages can also contain metadata such as IDs, names, and tool-call information.
# 8. A conversation is typically represented as a list of messages.
# 9. LangChain uses messages to maintain conversation context and state.
# 10. Typical flow: SystemMessage → HumanMessage → AIMessage → ToolMessage → AIMessage.

# Messages

# Messages are the fundamental unit of context for models in LangChain. They represent the input and output of models, carrying both the content and metadata needed to represent the state of a conversation when interacting with an LLM. Messages are objects that contain:
# • Role - Identifies the message type (e.g. system, user)
# • Content - Represents the actual content of the message (like text, images, audio, documents, etc.)
# • Metadata - Optional fields such as response information, message IDs, and token usage

# LangChain provides a standard message type that works across all model providers, ensuring consistent behavior regardless of the model being called.

import os
from dotenv import load_dotenv
load_dotenv()

from langchain_openai import ChatOpenAI

model = ChatOpenAI(
    model="nvidia/nemotron-3-ultra-550b-a55b:free",
    base_url="https://openrouter.ai/api/v1",
    api_key=os.getenv("OPENROUTER_API_KEY"),
)

# res=model.invoke("what is langgraph and how it is different from langchain")
# print(res)

"""
The Short Answer 
    LangChain is a framework for building LLM applications (chains, agents, RAG, integrations). It excels at linear sequences (A → B → C).
    LangGraph is a library for building stateful, cyclic, multi-actor applications built on top of LangChain. It excels at complex control flows (loops, branches, human-in-the-loop, long-running persistence).

Crucial Relationship: LangGraph does not replace LangChain. You use LangChain components (LLMs, prompts, tools, vector stores) inside LangGraph nodes.

1. What is LangChain? (The "Standard" Way)
LangChain was originally designed around Chains (sequences of steps) and Agents (an LLM deciding which tool to use next).

    Core Abstraction: Runnable / LCEL (LangChain Expression Language).
    Flow: Directed Acyclic Graphs (DAGs). Data flows one way: Input → Step 1 → Step 2 → ... → Output.
    State: Implicit. Passed as arguments between steps. No built-in "global memory" of the execution path.
    Agents (Old AgentExecutor): A hardcoded loop: LLM -> Tool -> Observation -> LLM -> .... Hard to customize the loop logic (e.g., "run tool twice then ask human").


Best for: RAG pipelines, simple extraction, linear prompt chains, basic tool use.

2. What is LangGraph? (The "Advanced" Way)
LangGraph models applications as Graphs (Nodes and Edges) with a central State object. It is inspired by Pregel (Google's graph processing) and Apache Beam.


    Core Abstractions:
        
            State: A shared data structure (TypedDict/Pydantic) passed between all nodes. Acts as the "scratchpad."
            Nodes: Functions (sync/async) that receive State, do work (call LLM, tool, DB), and return partial State updates.
            Edges: Determine the next node.
                
                    Direct: A → B.
                    Conditional: "If state['decision'] == 'tool' go to ToolNode, else go to End."
                
            
            Cycles/Loops: Explicitly supported (A → B → A).
            Persistence (Checkpointing): Killer Feature. Automatically saves State after every node to a checkpointer (SQLite, Postgres, Redis, Memory).
                
                    Enables: Human-in-the-loop (pause graph, wait for human input, resume), Time Travel (rewind to previous step), Fault Tolerance (restart from crash point).
                
            
            Multi-Agent: Native support for multiple agents passing state to each other.
        
    


Best for: Complex Agents, Multi-agent systems, Human-in-the-loop, Long-running processes, Cycles/ReAct loops with custom logic.



3. Detailed Comparison Table


    
        Feature
        LangChain (LCEL / Chains)
        LangGraph
    
    
        Control Flow
        Linear / DAG (A → B → C). Hard to do loops.
        Cyclic Graphs (A → B → A). Native loops & branching.
    
    
        State Management
        Implicit (inputs/outputs). Global state requires RunnableWithMessageHistory or manual passing.
        Explicit Central State. Every node reads/writes same State object.
    
    
        Persistence
        Manual / RunnableWithMessageHistory (chat history only).
        Built-in Checkpointing (Full state snapshot per step).
    
    
        Human-in-the-Loop
        Difficult / Hacky (break chain, wait, restart chain).
        Native (interrupt(), pause, resume with new input).
    
    
        Streaming
        Token streaming (LLM output).
        Token streaming + Step streaming (see every node execute).
    
    
        Debugging/Observability
        LangSmith traces (linear spans).
        LangSmith traces (graph visualization, state at each node).
    
    
        Agent Architecture
        AgentExecutor (Fixed ReAct loop logic).
        Custom Agent Logic (You define the loop: Plan → Execute → Reflect → Loop).
    
    
        Multi-Agent
        Possible but awkward (nesting chains).
        Native (Sub-graphs, Swarm, Supervisor patterns).
    
    
        Learning Curve
        Lower (Start here).
        Higher (Graph theory concepts, state reducers).
    




4. Code Comparison: "Tool Calling Agent"

LangChain (LCEL / create_tool_calling_agent)
The logic of the loop (call LLM -> check tool calls -> call tools -> repeat) is hidden inside AgentExecutor.
from langchain.agents import create_tool_calling_agent, AgentExecutor
from langchain_core.prompts import ChatPromptTemplate

prompt = ChatPromptTemplate.from_messages([
 ("system", "You are helpful"), ("user", "{input}"), ("placeholder", "{agent_scratchpad}")
])
agent = create_tool_calling_agent(llm, tools, prompt)
executor = AgentExecutor(agent=agent, tools=tools, verbose=True)
result = executor.invoke({"input": "What's the weather in SF?"})
# You cannot easily say: "After 2 tool calls, ask a human for confirmation."


LangGraph (StateGraph)
You write the loop logic explicitly. Total control.
from langgraph.graph import StateGraph, END
from typing import TypedDict, Annotated
import operator

# 1. Define State
class AgentState(TypedDict):
 messages: Annotated[list, operator.add] # Reducer: appends messages

# 2. Define Nodes
def call_model(state: AgentState):
 response = llm_with_tools.invoke(state['messages'])
 return {"messages": [response]}

def call_tools(state: AgentState):
 # Custom tool calling logic here
 last_msg = state['messages'][-1]
 tool_results = tool_node.invoke({"messages": [last_msg]})
 return {"messages": tool_results}

# 3. Define Routing Logic (Conditional Edge)
def should_continue(state: AgentState):
 last_msg = state['messages'][-1]
 if last_msg.tool_calls:
 return "tools"
 return "end"

# 4. Build Graph
workflow = StateGraph(AgentState)
workflow.add_node("agent", call_model)
workflow.add_node("tools", call_tools)
workflow.set_entry_point("agent")
workflow.add_conditional_edges("agent", should_continue, {"tools": "tools", "end": END})
workflow.add_edge("tools", "agent") # THE CYCLE

# 5. Compile with Checkpointer (Persistence!)
from langgraph.checkpoint.sqlite import SqliteSaver
memory = SqliteSaver.from_conn_string(":memory:")
app = workflow.compile(checkpointer=memory)

# 6. Run (Thread ID enables persistence/resumption)
config = {"configurable": {"thread_id": "user-123"}}
app.invoke({"messages": [HumanMessage("Weather in SF?")]}, config=config)

# LATER: Human-in-the-loop
# app.update_state(config, {"messages": [HumanMessage("User said: Yes, proceed")]})
# app.invoke(None, config=config) # Resumes from exact pause point




5. When to use which?

✅ Use Standard LangChain (LCEL) if:

    You are building RAG (Retrieval → Prompt → LLM).
    You have linear pipelines (Extract → Summarize → Translate).
    You need simple tool use (Single turn, or standard ReAct agent).
    You are prototyping fast and don't need cycles/persistence.


✅ Use LangGraph if:

    You need Cycles: Agent must reflect, retry, or loop until condition met.
    Human-in-the-Loop: You need to pause execution, get human approval/input, and resume exactly where you left off.
    Long-running Jobs: Processes taking hours/days (needs persistence to survive server restarts).
    Complex Multi-Agent: Supervisor routing to specialized sub-agents; agents collaborating.
    Stateful Conversations: You need to manipulate history explicitly (e.g., "delete last 2 messages," "inject system message mid-convo").
    Deterministic Control: You want to see and control the exact flow logic (if/else/loops) in code, not hidden in a class.

6. Migration Path (They work together)
You do not rewrite everything.

    Keep your LangChain prompts, llms, embedding models, vector stores, document loaders, output parsers.
    Wrap your LangChain Runnables inside LangGraph Nodes.
        # A LangChain chain becomes a LangGraph Node
my_rag_chain = retriever | prompt | llm | parser

def rag_node(state: GraphState):
 result = my_rag_chain.invoke(state['question'])
 return {"answer": result}

    
    Use LangGraph to orchestrate when and how often that chain runs.


Summary

    LangChain = The Toolbox (Hammers, screws, wood, LLM wrappers, Vector DB integrations).
    LangGraph = The Architect/Foreman (Blueprints, State management, Control flow, "Build this wall, then check with human, then paint it, loop until perfect").

"""

# Message Prompt vs text prompts
# AIMessgae, HumanMessage, systemMessage, toolmessage